/**
 * @link https://www.typescriptlang.org/docs/handbook/utility-types.html
 */
export type SearchKeys =
    | 'crossJoin'
    | 'distinct'
    | 'first'
    | 'groupBy'
    | 'having'
    | 'inRandomOrder'
    | 'join'
    | 'latest'
    | 'leftJoin'
    | 'limit'
    | 'offset'
    | 'onlyTrashed'
    | 'orWhere'
    | 'orWhereBetween'
    | 'orWhereColumn'
    | 'orWhereIn'
    | 'orWhereNotBetween'
    | 'orWhereNotIn'
    | 'orWhereNotNull'
    | 'orWhereNull'
    | 'orderBy'
    | 'orderByDesc'
    | 'rightJoin'
    | 'select'
    | 'sharedLock'
    | 'skip'
    | 'take'
    | 'withTrashed'
    | 'where'
    | 'whereBetween'
    | 'whereColumn'
    | 'whereDate'
    | 'whereDay'
    | 'whereIn'
    | 'whereMonth'
    | 'whereNotBetween'
    | 'whereNotIn'
    | 'whereNotNull'
    | 'whereNull'
    | 'whereTime'
    | 'whereYear';
